version: '3'
services:
 sonarqube:
  image: sonarqube:8.9.7-community
  hostname: sonarqube
  container_name : sonarqube
  volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
  ports:
  - "9000:9000"
 nexus:
  image: sonatype/nexus3
  hostname: nexus
  container_name: nexus
  volumes:
      - nexus_data:/sonatype-work
  ports:
      - "8081:8081"
 mysqldb:
  container_name: achat-projet
  image: mysql:8
  restart: unless-stopped
  environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=achatdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
  ports:
  - "3306:3306"
  volumes:
      - /home/mysql/data:/var/lib/mysql

 spring_app:
  image: mariemglaa/repo:372
  container_name: cnt_achat
  restart: on-failure
  ports:
      - 8089:8089
  environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  depends_on:
    - mysqldb
    
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  nexus_data:
  db:

