version: '2.2'
services:
 sonarqube:
  image: sonarqube:8.9.7-community
  hostname: sonarqube
  container_name : sonarqube
  volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
  ports:
  - "9000:9000"
 nexus:
  image: sonatype/nexus3
  hostname: nexus
  container_name: nexus
  volumes:
      - nexus_data:/sonatype-work
  ports:
      - "8081:8081"
 mysqldb:
  image: mysql:5.7
  restart: unless-stopped
  environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=achatdb
  ports:
  - "3306:3306"
  volumes:
      - db:/var/lib/mysql
 app:
  image: mariemglaa/repo:261
  container_name: achat
  restart: on-failure
  ports:
      - 8089:8089
  environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
        volumes:
      - .m2:/root/.m2
  stdin_open: true
  tty: true
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  nexus_data:
  db:
