version: '3'
services:
 mysqldb:
  container_name: achat-projets
  image: mysql:8
  restart: unless-stopped
  environment:
      - MYSQL_DATABASE=achatdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
  ports:
  - 3306:3306
 # volumes:
 #    - /home/mysql/data:/var/lib/mysql

 spring_app:
  image: mariemglaa/repo:384
  container_name: cntr_achat
  restart: on-failure
  ports:
      - 8089:8089
  environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/achatdb
  depends_on:
    - mysqldb
