version: '3'
services:
 mysqldb:
  container_name: achat-projets
  image: mysql:8
  restart: unless-stopped
  environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=achatdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
  ports:
  - 3306:3306
  volumes:
      - /home/mysql/data:/var/lib/mysql

 spring_app:
  image: mariemglaa/repo:372
  container_name: cntr_achat
  restart: on-failure
  ports:
      - 8089:8089
  environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  depends_on:
    - mysqldb
