version: '3'
services:
 mysqldb:
  container_name: achat-projetsss
  image: mysql:8
  restart: unless-stopped
  environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
  ports:
   - 3306:3306
 # volumes:
 #    - /home/mysql/data:/var/lib/mysql

 spring_app:
  image: backend
  container_name: cntr_achat
  restart: on-failure
  ports:
      - 8089:8089
  environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/achatdb
  depends_on:
    - mysqldb
